server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  instance:
    hostname: localhost
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  datasource:
    url: jdbc:postgresql://192.168.65.187:5432/projectdb
    username: dwsc
    password: dwsc
    driver: org.postgresql.Driver
