server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  instance:
    hostname: localhost
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
